image: Visual Studio 2019
version: 1.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
environment:
  CODECOV_REPO_TOKEN:
    secure: TODO
configuration:
  - Release
test_script:
  - dotnet test --configuration Release /p:CollectCoverage=true /p:Exclude='\"[*TestAdapter*]*,[nunit]*\"' /p:CoverletOutputFormat=cobertura /p:CoverletOutput="../coverage/MongoDB.Bson.Path.coverage.xml" /p:CopyLocalLockFileAssemblies=true MongoDB.Bson.Path.Test/MongoDB.Bson.Path.Test.csproj
after_test:
- ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f "coverage/MongoDB.Bson.Path.coverage.xml" -t $env:CODECOV_REPO_TOKEN
for:
-
  branches:
    only:
      - master

  build:
    publish_nuget: true

  deploy:
    provider: NuGet
    api_key:
      secure: TODO
    skip_symbols: false
